config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }
  
  namespace :admin do 
      resources :restaurants
  end
    
  resources :blogs 
  resources :restaurants do
      resources :reviews, except: [:show, :index]
      
  end
    
    resources :reservations
    resources :tables
    resources :reviews
    
    
    
    
    root 'restaurants#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
end

app/models/reservation.rb
class ReservationValidator < ActiveModel::Validator
  def validate(reservation)
      @reserved_times = Reservation.where( :table_id => reservation.table_id)
      @max_seats = Table.where( :id => reservation.table_id)
      @max_seats.each do |s|
      @reserved_times.each do |r|
    if reservation.time == r.time || reservation.customers > s.seats
      reservation.errors[:time] << "Time is taken"
    end
      end
      end
  end
end

class Reservation < ApplicationRecord
    belongs_to :table
    belongs_to :user
    validates_with ReservationValidator, on: :create
    
    validates_uniqueness_of :time
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :region
    belongs_to :country
    has_one_attached :image
    validates :title, :description, :region_id, presence: true
    has_many  :line_items, inverse_of: :orders 
    has_one :tables, dependent: :destroy
    has_many :reviews, dependent: :destroy
    
    validates_uniqueness_of :title
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :restaurant
end

app/models/table.rb
class Table < ApplicationRecord
    belongs_to :restaurant
    has_many :reservations
    
    validates :seats, presence: true
    validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
    has_many :reservations
    has_many :reviews, dependent: :destroy
    validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :error
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show]

  def index
    @blogs = Blog.all
  end

  def show
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :find_restaurant, only: [:show]
    before_action :find_table, only: [:show]
    
    
    def index
        
        if params[:region].blank?
            @restaurants = Restaurant.all.order("created_at DESC")
        else
            @region_id = Region.find_by(name: params[:region]).id
            @restaurants = Restaurant.where(region_id: @region_id).order("created_at DESC")
        end
    end
    
    def show
        @user = current_user
        @reservation = Reservation.new(user_id: @user, table_id: @table, time: @time, user: @user)
        @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    end
    
    def new
        @restaurant = Restaurant.new
    end
    
    def create
           @restaurant = Restaurant.new(restaurant_params)
         if @restaurant.save
             @table = Table.new(restaurant_id: @restaurant.id, price: 25, seats: 4)
             @table.save
             @restaurant.table_id = @table.id
             @restaurant.save

              redirect_to restaurants_path, notice: 'The restaurant was created!'
         else 
              render 'new'
         end 
    end
    
    
    
    
private
    def restaurant_params
        params.require(:restaurant).permit(:title, :description, :region_id, :image, :table_id)
    end
    
   
    
    def find_restaurant
        @restaurant = Restaurant.find(params[:id])
    end
    
    def find_table
        @table = Table.find(params[:id] = @restaurant.id)
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
    before_action :set_restaurant

  
  def new
    @review = Review.new
  end

  
  def edit
  end


  def create
        @review = Review.new(review_params)
        @review.user_id = current_user.id
        @review.restaurant_id = @restaurant.id
        if @review.save
            redirect_to @restaurant, notice: 'The review was created!'
        else 
            render 'new'
        end 
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
      @restaurant = Restaurant.find(params[:id] = @review.restaurant_id )
    @review.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_review
      @review = Review.find(params[:id])
    end
    
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

   
    def review_params
      params.require(:review).permit(:user_id, :rating, :comment)
    end
    
    
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def login_helper style
        if current_user.is_a?(User)
            link_to "Logout", destroy_user_session_path, mehtod: :delete, class: style
        else
            (link_to "Login", new_user_session_path, class: style)
            "<br>" +
            (link_to "Register", new_user_registration_path, class: style)
        end
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
    
    def blog_image(blog_id)
    blog = Blog.find!(blog_id)
    if blog.image.attached?
        image_tag blog.image
    else
        image_tag 'default_avatar.jpg'
    end
end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
    def image_generator(height:, width:)
		"https://placeholder.com/#{height}x#{width}"
	end

	def restaurant_img img, type
		if img.model.main_image? || img.model.thumb_image
			img.to_s
		elsif type == 'thumb'	
			image_generator(height: '350', width: '200').to_s
		elsif type == 'main'
			image_generator(height: '600', width: '400').to_s
		end			
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
  
   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CleverBird</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   
    
    
  </head>
  
    

  <body>
      <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
         <header class="masthead mb-auto">
            <%= render'shared/nav' %>  
         </header>
         <% if flash[:error] %>
             <div class="alert alert-warning" role="alert">
                  <p class="flashalert"><%= error %></p>
             </div>
         <% end %>
         <%= yield %>
         <footer class="mastfoot mt-auto">
         <%= render 'shared/footer' %>
          </footer>
      </div>
  </body>



    
</html>

app/views/layouts/restaurant.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CleverBird</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   
    
    
  </head>
  
    

  <body>
      <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
         <header class="masthead mb-auto">
            <%= render'shared/nav' %>  
         </header>
         <%= yield %>
         <footer class="mastfoot mt-auto">
         <%= render 'shared/footer' %>
          </footer>
      </div>
  </body>



    
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p> We are a site that provide offers of up to 50% off meals for up to 4 poeple.</p>
<p>By exchanging 6 euro for a reservation you can save up to 25 euro per person. It is as easy as a click of a button</p>

app/views/shared/_error_messages.html.erb
<% if @restaurant.errors.any? %>
    <div>
       <p><%= pluralize(@restaurant.errors.count, "error") %> prevented this restaurant from saving.</p>
          <ul>
               <% @restaurant.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
               <% end %>
          </ul> 
        
    </div>
<% end %>

app/views/shared/_footer.html.erb
    <div class="inner">
      <p>Copyright &copy; CleverBird 2018</p>
    </div>

app/views/shared/_nav.html.erb
<div class="inner">
          <h3 class="masthead-brand">CleverBird</h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link" href="<%= root_path %>">Home</a>
            <a class="nav-link" href="<%= restaurants_path %>">Restaurants</a>
            <a class="nav-link" href="#">     .</a>
            <% if current_user.present? %>
               <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_user.first_name %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="<%= edit_user_registration_path(current_user) %>">Profile</a>
                  <a class="dropdown-item" href="<%= reservations_path %>">Reservations</a>
                  <a class="dropdown-item" href="<%= blogs_path %>">Blogs</a>
                  <a class="dropdown-item" href="<%= destroy_user_session_path %>">Log Out</a>
                </div>
               </li>
            <% else %>
                    <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
                    <a class="nav-link" href="<%= new_user_session_path %>">Sign In</a>
            <% end %>
              </nav>
</div>

app/views/shared/_region.html.erb
    
<% Category.all.each do |category| %>
  <li>
  <%= link_to category.name, posts_path(category: category.name) %>
  </li>
<% end %>
     
<!--
    <div class="restaurant_regions">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">By Region
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <% Region.all.each do |region| %>
      <li>
      <%= link_to region.name, restaurants_path(region: region.name) %>
      </li>
      <% end %>
      <li><a href="<%= restaurants_path %>">All Regions</a></li> 
      </ul>
      </li>
</div>-->