config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }
  
  namespace :admin do 
      resources :restaurants
  end
    
  resources :blogs 
  resources :restaurants do
      resources :reviews, except: [:show, :index]
      
  end
    
    resources :reservations
    resources :tables
    resources :reviews
    
    
    
    
    root 'restaurants#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
end

app/controllers/admin/tables_controller.rb
class Admin::TablesController < Admin::AdminController
before_action :find_table, only: [:show, :edit, :update, :destroy]

  
    
    def index
        if params[:region].blank?
          @restaurants = Restaurant.all.order("created_at DESC")
        else
          @region_id = Region.find_by(name: params[:region]).id
          @restaurants = Restaurant.where(region_id: @region_id).order("created_at DESC")
        end
    end
    
    def show
        @restaurant = Restaurant.find(params[:id] == @table.id)
        @user = current_user
    end
    
    def new
        @table = Table.new
    end
    
    def create
        @table = Table.new(table_params)
        if @table.save
           redirect_to admin_tables_path, notice: 'The table was created!'
        else 
           render ‘new’
        end 
    end
    
    def edit
        
    end
    
    def update
        if @table.update(table_params)
          redirect_to @table, notice: 'Update successful'
        else
          render ‘edit’
        end
    end

    def destroy
        @table.destroy
        redirect_to root_path, notice: 'Table destroyed'
    end   
    
    def self.get_details
        @table = Table.find(params[:id])
    end 



private
    def table_params
        params.require(:table).permit(:price, :seats, :restaurant_id)
    end
    
    def find_table
        @table = Table.find(params[:id])
    end

    
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
    
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/index.html.erb
       
  <main role="main" class="inner cover">
      
  
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">CleverBird Restaurants</h1>
          <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        </div>
      </section>
      <div class="container">
          <div class="nav-scroller py-1 mb-2">
                <nav class="nav d-flex justify-content-between">
                    <a class="p-2 text-muted" href="<%= restaurants_path %>">All Regions</a>
                     <% Region.all.each do |region| %>
                        <a class="p-2 text-muted" href="#"><%= link_to region.name, restaurants_path(region: region.name) %></a>
                     <% end %>

                </nav>
          </div>
      </div>
    <br/>
       
    
        <div class="row mb-2">
    <div class="col-md-12">
     <% @restaurants.each do |restaurant| %>
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-lg h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary"><a href="<%= restaurant_path(restaurant) %>" class="card-text"><h3><%= restaurant.title %></h3></a></strong>
          
          <div class="mb-1 text-muted">€50</div>
          <p class="card-text mb-auto"><%= restaurant.description %></p>
          
        </div>
        <div class="col-auto d-none d-lg-block">
          <a class="img-fluid" > <%= image_tag(restaurant.image, size: "265x255") if restaurant.image.attached?%></a>
        </div>
      </div>
       <% end %>
    </div>
    
  </div>    
    


          
</main>

app/views/tables/show.html.erb
<div class="container">
   <div class="row">
    
      <div class="title-heading">
          <h1><%= @table.restaurant.title %></h1>
      </div>
       <div class="col-md-12">
           <p>Seats : <%= @table.seats %></p>
       </div>
       
       <div class="col-md-12">
           <p>Price : <%= @table.price %></p>
       </div>
      
   </div>
   
   
   
</div>