config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }
  
  namespace :admin do 
      resources :restaurants
  end
    
  resources :blogs 
  resources :restaurants do
      resources :reviews, except: [:show, :index]
      
  end
    
    resources :reservations
    resources :tables
    resources :reviews
    
    
    
    
    root 'restaurants#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :region
    belongs_to :country
    has_one_attached :image
    validates :title, :description, :region_id, presence: true
    has_many  :line_items, inverse_of: :orders 
    has_one :tables, dependent: :destroy
    has_many :reviews, dependent: :destroy
    
    validates_uniqueness_of :title
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::AdminController
#    before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
    
    def index
      if params[:region].blank?
        @restaurants = Restaurant.all.order("created_at DESC")
      else
        @region_id = Region.find_by(name: params[:region]).id
        @restaurants = Restaurant.where(region_id: @region_id).order("created_at DESC")
      end
    end
    
    def show
    end
    
    def new
        @restaurant = Restaurant.new
    end
    
    def create
           @restaurant = Restaurant.new(restaurant_params)
         if @restaurant.save
             @table = Table.new(restaurant_id: @restaurant.id, price: 25, seats: 4)
             @table.save
             @restaurant.table_id = @table.id
             @restaurant.save

              redirect_to restaurants_path, notice: 'The restaurant was created!'
         else 
              render 'new'
         end 
    end
    
    def destroy
        @restaurant.destroy
        @table = Table.where(:restaurant_id => @restaurant.id)
        @table.destroy
        redirect_to root_path, notice: 'Restaurant destroyed'
    end 
    
    def edit
        
    end
    
    def update
        if @restaurant.update(restaurant_params)
          redirect_to @restaurant, notice: 'Update successful'
     else
          render ‘edit’
     end
    end
    
    def destroy
        @restaurant.destroy
     redirect_to root_path, notice: 'Restaurant destroyed'
    end    
    
    
private
    def restaurant_params
        params.require(:restaurant).permit(:title, :description, :region_id, :image)
    end
    
    def find_restaurant
        @restaurant = Restaurant.find(params[:id])
    end
    
    
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :find_restaurant, only: [:show]
    before_action :find_table, only: [:show]
    
    
    def index
        
        if params[:region].blank?
            @restaurants = Restaurant.all.order("created_at DESC")
        else
            @region_id = Region.find_by(name: params[:region]).id
            @restaurants = Restaurant.where(region_id: @region_id).order("created_at DESC")
        end
    end
    
    def show
        @user = current_user
        @reservation = Reservation.new(user_id: @user, table_id: @table, time: @time, user: @user)
        @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    end
    
    def new
        @restaurant = Restaurant.new
    end
    
    def create
           @restaurant = Restaurant.new(restaurant_params)
         if @restaurant.save
             @table = Table.new(restaurant_id: @restaurant.id, price: 25, seats: 4)
             @table.save
             @restaurant.table_id = @table.id
             @restaurant.save

              redirect_to restaurants_path, notice: 'The restaurant was created!'
         else 
              render 'new'
         end 
    end
    
    
    
    
private
    def restaurant_params
        params.require(:restaurant).permit(:title, :description, :region_id, :image, :table_id)
    end
    
   
    
    def find_restaurant
        @restaurant = Restaurant.find(params[:id])
    end
    
    def find_table
        @table = Table.find(params[:id] = @restaurant.id)
    end
    
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
    def image_generator(height:, width:)
		"https://placeholder.com/#{height}x#{width}"
	end

	def restaurant_img img, type
		if img.model.main_image? || img.model.thumb_image
			img.to_s
		elsif type == 'thumb'	
			image_generator(height: '350', width: '200').to_s
		elsif type == 'main'
			image_generator(height: '600', width: '400').to_s
		end			
	end
end

app/views/restaurants/_form.html.erb
<div class="container">
   <div class="row">
    <%= simple_form_for([ @restaurant]) do |f| %>
     <%= render 'shared/error_messages' %>
     <%= f.association :country, include_blank: false, label: "Choose Country" %>
     <%= f.association :region, include_blank: false, label: "Choose Region" %>
     
     <div class="field">
         <%= f.input :title %>
     </div>
     
     <div class="field">
         <%= f.input :image %>
     </div>
     
     <div class="field">
         <%= f.input :description, placeholder: 'Type the restaurant tect here' %>
     </div>
     
     <div class="action">
         <%= f.submit %>
     </div>
     <% end %>
    </div>
</div>

app/views/restaurants/_payment.html.erb
<% if !@reservation.persisted? %>
    <h4 class="subtitle is-4">Payment</h4>
    
    <div class="notification is-light has-text-centered">
        <i class="fa fa-credit-card"></i>
        6 Euro for 50% off a meal of up to <%= @reservation.table.price %>
        <span class="block mb4"></span>
    </div>
    
    <div class="form-row">
        <label for="card-element" class="label">
            Enter Credit Card or Debit Card.
        </label>
        
        <div id="card-element" class="form-control">
<!--            Stripe element will be sorted here-->
        </div>
        
        <div id="card-errors" role="alert"></div>
    </div>
    
    <% if current_user.stripe_id.present? %>
    
        <div class="last-card bg-light pa4 border-radius-3 mt4">
            <h5 class="is-6 title pt2">Previously Used Card</h5>
            <table class="table is-narrow bg-light is-fullwidth">
                <thead>
                    <th>Card Brand</th>
                    <th>Last 4 Digits</th>
                    <th>Expiration Month</th>
                    <th>Expiration Year</th>
                </thead>
                
                <tr>
                    <td>current_user.card_brand</td>
                    <td>current_user.card_last4</td>
                    <td>current_user.card_exp_month</td>
                    <td>current_user.card_exp_year</td>
                </tr>
            </table>
        </div>
    <% end %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render 'restaurants/form' %>

app/views/restaurants/home.html.erb
  <main role="main" class="inner cover">
    <h1 class="cover-heading">CleverBird.</h1>
    <p class="lead">Get luxury dining for a fraction of the price. Deals up to 50% off Dublin's finest restaurants in just a few clicks of a button.</p>
    <p class="lead">
      <a href="restaurants" class="btn btn-lg btn-secondary">Get Started</a>
    </p>
  </main>
           
          
  
       
  

app/views/restaurants/index.html.erb
       
  <main role="main" class="inner cover">
      
  
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">CleverBird Restaurants</h1>
          <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        </div>
      </section>
      
    <br/>
       
    
        <div class="row mb-2">
    <div class="col-md-12">
    <div class="container">
          <div class="nav-scroller py-1 mb-2">
                <nav class="nav d-flex justify-content-between">
                    <a class="p-2 text-muted" href="<%= restaurants_path %>">All Regions</a>
                     <% Region.all.each do |region| %>
                        <a class="p-2 text-muted" href="#"><%= link_to region.name, restaurants_path(region: region.name) %></a>
                     <% end %>

                </nav>
          </div>
      </div>
     <% @restaurants.each do |restaurant| %>
     <div class="rest">
         <div class="row ">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary"><a href="<%= restaurant_path(restaurant) %>" class="card-text"><h3><%= restaurant.title %></h3></a></strong>
          <p class=""><%= restaurant.description %></p>
          
        </div>
        <div class="col-auto d-none d-lg-block">
          <a class="img-fluid" > <%= image_tag(restaurant.image, size: "265x255") if restaurant.image.attached?%></a>
        </div>
      </div>
     </div>
      
       <% end %>
    </div>
    
  </div>    
    


          
</main>

<!--
<div class="album text-muted">
   <div class="container">
      <div class="row">
        
         <% @restaurants.each do |restaurant| %>
  <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
           <%= image_tag(restaurant.image, size: "150x150") if restaurant.image.attached?%>
           <p class="card-text">
            <span><%= link_to restaurant.title, restaurant_path(restaurant) %></span>
            <%= restaurant.description %>
          </p>
    </div>
 </div>
<% end %>
      </div>
   </div>
</div>
-->

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/restaurants/show.html.erb
     <div class="container-fluid">
       <div class="row row-rest">
           <div class="col-md-12">
                <div class="title-heading">
                   <h1><%= @restaurant.title %></h1>
                </div>
           </div>
         
          <div class="col-md-6">
               <p><br />Price : €<%= @table.price %></p>
               <p><br />Rating : <%= @reviews.average(:rating) %></p>
               <p>Seats: <%= @table.seats %></p>
               <p><%= @restaurant.description %></p>
          </div>
          <div class="col-md-6">
               <br /><%= image_tag(@restaurant.image, size: "295x205") if @restaurant.image.attached?%>
               <div class="col-md-12">
                   <%= link_to 'Review', new_restaurant_review_path(@restaurant), class: "btn btn-secondary" %>
              
                    <%= link_to 'Book', new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
             
                    <%= link_to 'Reserved', reservations_path, class: "btn btn-secondary" %>
              </div>
          </div>
          
           <div class=" col-md-12 row-restbook">
                <h3><br  />Book Now</h3>
                <% if current_user.present? %>
                <P><%= render 'reservations/form' %></P>
                <% else %>
                <btn><a href="<%= new_user_registration_path %>">Sign Up</a></btn>
                <btn><a href="<%= new_user_session_path %>">Sign In</a></btn>
                <% end %>
           </div>
           
           <div class="col-md-6 ">
               <h1 class="review_title"><br />Reviews</h1>
               <h3><%= @restaurant.title%></h3>
               
               <% if @reviews.blank? %>
                   <h4>No reviews just yet, want to be the first to comment?</h4>
                   <%= link_to 'write a review', new_restaurant_review_path(@restaurant), class: "btn btn-danger" %>
               <% else %>
                   <% @reviews.each do |review| %>
                       <div class="reviews">
                           <p><br />User : <%= review.user.first_name %> <%= review.user.last_name %></p>
                           <p>rating : <%= review.rating %></p>
                           <p>Comment : <%= review.comment %></p>
                          
                            <% if current_user.present? && @current_user.id == review.user_id %>
                           <p><%= link_to "Delete Comment", restaurant_review_path( review.restaurant.id, review ), data: { confirm: "Are you sure?" }, method: :delete %></p>
                           <% end %>
                       </div>
                   <% end %>
                   
                   <% if current_user.present? %>
                   <div class="reviewers" %>
                   <%= link_to 'write a review', new_restaurant_review_path(@restaurant), class: "btn btn-secondary"%>
                   </div>
                   <% end %>
                <% end %>
           </div>
       </div>
     </div>